// === SOURCE URLS ===
const U={
  S:'https://www.gigaenergy.com',
  A:'https://www.gigaenergy.com/about',
  AR:'https://www.gigaenergy.com/giga-box-air',
  HY:'https://www.gigaenergy.com/giga-box-hydro',
  G:'https://www.gigaenergy.com/giga-power-systems',
  SD:'https://www.gigaenergy.com/site-origination-development',
  AI:'https://www.gigaenergy.com/industries/ai-infrastructure',
  F:'https://www.prnewswire.com/news-releases/giga-energy-announces-new-houston-manufacturing-facility-to-expand-us-transformer-production-to-power-ai-infrastructure-302643008.html',
  GP:'https://www.prnewswire.com/news-releases/giga-energy-launches-giga-power-systems-to-help-data-centers-monetize-flexibility-and-reduce-energy-costs-302659426.html',
  IV:'https://pulse2.com/giga-energy-profile-matt-lohstroh-interview/',
  BR:'https://www.gigaenergy.com/blog/data-center-profit-margin',
  BS:'https://www.gigaenergy.com/blog/maximize-revenue-southwest-power-pool',
  BA:'https://www.gigaenergy.com/blog/how-giga-builds-ai-ready-data-centers',
  // General electrical knowledge sources
  EE:'https://en.wikipedia.org/wiki/Electric_power_distribution',
  GR:'https://en.wikipedia.org/wiki/North_American_Electric_Reliability_Corporation',
  BL:'https://en.wikipedia.org/wiki/Northeast_blackout_of_2003',
  TX:'https://en.wikipedia.org/wiki/2021_Texas_power_crisis'
};

// === QUESTIONS ===
const Q={transformers:{
0:[
// Electrical fundamentals — the vocabulary you need before Level 1
{q:"What does 'voltage' measure in an electrical system?",o:["The speed of electricity","The electrical pressure that pushes current through a wire","The physical size of the wire","The cost per unit of electricity"],a:1,e:"Voltage is electrical pressure. Just like water pressure pushes water through pipes, voltage pushes electrical current through wires. Higher voltage = more push. Power plants generate at extremely high voltage (hundreds of thousands of volts) and transformers step it down for safe use. You'll hear 'kV' (kilovolts = thousands of volts) constantly in this industry.",s:U.EE},
{q:"What does 'kVA' stand for?",o:["Kilowatt Voltage Amp","Kilovolt-Ampere","Kilo Varied Amperage","Kilowatt Visual Amp"],a:1,e:"kVA = kilovolt-amperes. It measures the total electrical capacity of equipment like transformers and generators. Think of it like the size of a pipe: a bigger kVA rating means the equipment can handle more power flowing through it. 1 MVA = 1,000 kVA. When someone says 'I need a 2,500 kVA transformer,' they're telling you how much power capacity they need.",s:U.EE},
{q:"What is the difference between AC and DC power?",o:["AC is faster, DC is slower","AC alternates direction back and forth; DC flows in one constant direction","AC is used in batteries; DC is used in homes","They are the same thing with different names"],a:1,e:"AC (Alternating Current) switches direction 60 times per second (in the US). DC (Direct Current) flows one way, like from a battery. The entire power grid runs on AC because it's easy to step up and down with transformers. Your phone charger converts AC from the wall to DC for the battery. Thomas Edison championed DC; Nikola Tesla championed AC. Tesla won — and that's why your outlets deliver AC.",s:U.EE},
{q:"What does 'amperage' (amps) measure?",o:["The amount of electrical current flowing through a wire","The voltage of a power line","The speed of electricity","The resistance of a wire"],a:0,e:"Amps measure the flow rate of electricity — how much current is actually moving through the wire. If voltage is the water pressure, amps are how much water is flowing. High amps = lots of current. This is why breakers are rated in amps: a 200-amp breaker protects against too much current flowing and causing a fire.",s:U.EE},
{q:"What is a 'watt' and how does it relate to volts and amps?",o:["Watts = Volts × Amps (it measures actual power being consumed)","Watts = Volts + Amps","Watts only apply to light bulbs","Watts and volts are the same thing"],a:0,e:"Watts = Volts × Amps. Watts measure actual power — how much work electricity is doing. A 100-watt light bulb uses 100 watts. A kilowatt (kW) = 1,000 watts. A megawatt (MW) = 1,000,000 watts (enough to power ~750 homes). In this industry, you'll constantly hear kW and MW when talking about facility power needs.",s:U.EE},
{q:"What does 'MW' stand for, and how much power is it?",o:["Micro-Watt — a tiny amount of power","Mega-Watt — 1 million watts, enough to power roughly 750 homes","Multi-Wire — a type of electrical connection","Maximum Wattage — the most power a device can use"],a:1,e:"MW = megawatt = 1,000,000 watts = 1,000 kW. It's the standard unit for talking about large power facilities. A single Bitcoin mining site might use 50 MW. A large data center campus could be 100+ MW. When customers say 'I need 20 MW,' they're talking about serious power infrastructure.",s:U.EE},
{q:"What is a 'circuit breaker' and what does it do?",o:["Generates electricity for a circuit","Measures how much power a circuit uses","Automatically cuts power when too much current flows, preventing fires and equipment damage","Converts AC power to DC power"],a:2,e:"A circuit breaker is a safety switch that automatically trips (opens) when current exceeds a safe level, protecting wires and equipment from overheating and fires. Think of it like a safety valve. Switchboards are full of circuit breakers — each one protects a different circuit. Breakers are rated in amps (e.g., a 200A breaker trips if current exceeds 200 amps).",s:U.EE},
{q:"What does 'MV' mean in electrical terminology?",o:["Maximum Voltage","Mega Volts","Medium Voltage (typically 1 kV to 35 kV)","Micro Voltage"],a:2,e:"MV = Medium Voltage, typically ranging from 1,000 volts (1 kV) to 35,000 volts (35 kV). This is the voltage level used to distribute power within industrial sites and campuses. Below MV is LV (Low Voltage, under 1 kV — what's in your house). Above MV is HV (High Voltage, 35 kV+) used for long-distance transmission. Knowing these ranges helps you recommend the right equipment.",s:U.EE},
{q:"What is 3-phase power, in the simplest terms?",o:["Power from three different power plants","Three separate power deliveries running together for higher capacity","Power that runs three times faster than normal","A backup power system with three generators"],a:1,e:"Imagine three separate electrical waves, each offset by a third of a cycle, running through three wires simultaneously. This delivers more power, more smoothly than a single wave (1-phase). Almost all commercial and industrial buildings use 3-phase. Homes use 1-phase. If a customer is running a data center, factory, or commercial building, they need 3-phase power.",s:U.EE},
{q:"What is ERCOT?",o:["A brand of electrical equipment","The organization that manages the Texas power grid","An electrical safety certification","A type of transformer"],a:1,e:"ERCOT = Electric Reliability Council of Texas. It operates the electrical grid for about 90% of Texas. Texas has its own grid, separate from the rest of the US, which is why ERCOT is unique. You'll also hear about SPP (Southwest Power Pool — Oklahoma, Kansas, etc.), PJM (the Mid-Atlantic/Midwest grid — the largest US market), and MISO (the Midwest grid). These are the markets where Giga operates.",s:U.GR},
{q:"What happened during the 2021 Texas power crisis, and why does it matter for the energy industry?",o:["A hurricane knocked out power lines","A record winter storm caused widespread grid failure, leaving millions without power for days","A cyberattack shut down the grid","Natural gas prices dropped to zero"],a:1,e:"In February 2021, Winter Storm Uri hit Texas with record cold. Natural gas plants froze, wind turbines iced over, and demand skyrocketed. Over 4.5 million homes lost power, some for days. Hundreds died. It exposed how vulnerable the grid is and drove massive investment in grid reliability and energy infrastructure — which is exactly what companies like Giga help build.",s:U.TX},
{q:"What does 'the grid' refer to in the energy industry?",o:["The internet backbone","The interconnected network of power plants, transmission lines, and distribution systems that deliver electricity","A type of solar panel array","The floor plan of a data center"],a:1,e:"The electrical grid is the entire system that generates, transmits, and distributes electricity — from power plants to the outlets in your wall. The US actually has three separate grids: the Eastern Interconnection, the Western Interconnection, and ERCOT (Texas). Understanding the grid helps you understand why transformers, substations, and switchboards matter — they're the equipment that makes the grid work.",s:U.EE},
{q:"What does 'UL Listed' mean on electrical equipment?",o:["Manufactured in the United States","Tested and certified by Underwriters Laboratories for safety","Uses ultra-low voltage","Unlimited lifetime warranty"],a:1,e:"UL (Underwriters Laboratories) is an independent safety testing organization. When equipment is 'UL Listed,' it means UL tested it and confirmed it meets safety standards. This matters because many building codes require UL-listed equipment, and many customers won't buy anything without it. It's a trust signal.",s:U.EE},
{q:"What does 'KAIC' mean on a switchboard or breaker rating?",o:["Kiloampere International Certification","Kilo Ampere Interrupting Capacity — how much fault current the equipment can safely handle","Kilowatt Average Industrial Current","A brand name for a type of breaker"],a:1,e:"KAIC = Kilo Ampere Interrupting Capacity. It measures how much fault current (a massive surge from a short circuit) the equipment can safely interrupt without exploding or catching fire. A 65 KAIC breaker can handle a 65,000-amp fault. Higher KAIC = safer in locations near large power sources. This comes up when specifying switchboards.",s:U.EE},
{q:"What caused the Northeast Blackout of 2003, and how many people were affected?",o:["A terrorist attack on power plants","A software bug caused a cascading failure across the grid, affecting 55 million people","Lightning struck a single transformer","A coal shortage during summer heat"],a:1,e:"On August 14, 2003, a software bug at an Ohio utility prevented operators from seeing that power lines were sagging into trees. The resulting cascading failure knocked out power across 8 US states and parts of Canada, affecting 55 million people. It was the largest blackout in North American history and led to mandatory reliability standards. It's a reminder of why grid infrastructure and monitoring matter.",s:U.BL},
{q:"What is a 'substation' in the power grid?",o:["A small portable generator","A facility that steps voltage up or down between transmission and distribution levels","An underground bunker for storing fuel","A secondary office for a utility company"],a:1,e:"A substation is a fenced facility (you've seen them — the ones with warning signs and humming equipment) where voltage gets stepped up or down. Power plants send electricity out at very high voltage for efficient long-distance transmission. Substations step it down to medium voltage for local distribution, and then further down for end users. They're the critical nodes in the grid.",s:U.EE},
{q:"What is 'demand response' in the energy market?",o:["When power companies increase supply to meet demand","When large electricity users reduce or shift their consumption in exchange for payments","When customers demand lower electricity prices","When backup generators respond to a power outage"],a:1,e:"Demand response is when large power users (like data centers or factories) agree to reduce their electricity consumption during peak demand periods in exchange for payments from the grid operator. It's essentially getting paid NOT to use power at certain times. This is one of the revenue streams that Giga Power Systems helps data centers capture.",s:U.GP}
],
1:[
{q:"What is the primary function of a power transformer?",o:["Steps voltage up or down for safe delivery","Generates electricity from fuel","Stores energy in batteries for later use","Converts AC power to DC power"],a:0,e:"Think of voltage like water pressure. Power plants send electricity at extremely high voltage (like a fire hose), but buildings need it at lower voltage (like a garden hose). A transformer adjusts that pressure up or down so electricity is safe and usable. This is what Giga sells most of.",s:U.S},
{q:"What is a padmount transformer, and where is it typically installed?",o:["Mounted on a utility pole above ground","Sits on a concrete pad on the ground, connected to underground lines","Installed inside a building's electrical room","Floats on a platform over water"],a:1,e:"A padmount is the big green metal box you see on the ground outside shopping centers or apartment complexes. It sits on a concrete pad and connects to underground power lines. For sales, padmounts are Giga's bread-and-butter product.",s:U.S},
{q:"What is the key difference between 1-phase and 3-phase power delivery?",o:["1-phase is newer technology that's replacing 3-phase","3-phase uses three times more fuel than 1-phase","1-phase serves residential loads; 3-phase serves commercial/industrial loads","They deliver identical power — the names are just regional terms"],a:2,e:"Think of it like lanes on a highway. 1-phase is a single lane, enough for homes and small shops. 3-phase is three lanes running together, delivering much more power for factories, data centers, and commercial buildings. When a customer needs serious power, they need 3-phase.",s:U.S},
{q:"Where is Giga Energy's new transformer manufacturing facility located?",o:["Los Angeles, CA","Austin, TX","Houston, TX","Denver, CO"],a:2,e:"Giga opened a 60,000 sq ft transformer factory in Houston, TX in early 2026. That's roughly the size of a football field. Having a US factory means faster production and delivery, which is a huge deal when competitors have 1-2 year wait times.",s:U.F},
{q:"Approximately how many transformers has Giga Energy manufactured to date?",o:["About 100","500+","1,000+","5,000+"],a:2,e:"Over 1,000 transformers built, plus 3.5+ GW (gigawatts) of total electrical equipment delivered. A gigawatt can power roughly 750,000 homes, so 3.5 GW is massive. This track record matters in sales because customers need to trust you can deliver.",s:U.A},
{q:"What is Giga's biggest competitive advantage when selling transformers?",o:["Lowest price guaranteed across all models","Fastest lead times in the industry (days to weeks vs. competitors' 1-2 years)","Largest physical transformer units available on the market","Most color and finish options for aesthetic installations"],a:1,e:"Speed is the killer sales advantage. Giga ships in-stock transformers in 1-2 days and builds custom ones in 12-14 weeks. Competitors like ABB, Eaton, and Siemens take 52-104+ weeks (that's 1-2 years). When a customer's project is stalled waiting for a transformer, every week of delay costs real money.",s:U.S},
{q:"What type of liquid is used inside most Giga transformers for cooling and insulation?",o:["Purified water","Mineral oil or FR3 natural ester fluid","Gasoline-based coolant","Liquid nitrogen"],a:1,e:"Most transformers are filled with special liquid for cooling and insulation, either mineral oil (petroleum-based) or FR3 (a plant-based, biodegradable alternative). Think of it like the coolant in a car engine. FR3 is the eco-friendly option with a higher fire safety rating.",s:U.S},
{q:"What does 'kVA' measure on a transformer's spec sheet?",o:["Shipping speed of the unit","Physical weight in kilograms","Power capacity in kilovolt-amperes","Maximum operating temperature"],a:2,e:"kVA stands for kilovolt-amperes. Think of it like engine horsepower but for electrical equipment. A 75 kVA transformer might power a small office building, while a 10,000 kVA unit powers a whole data center. When customers tell you their power needs, they'll use kVA.",s:U.S},
{q:"Who founded Giga Energy, and what is their background?",o:["A Fortune 500 energy conglomerate","Two Texas A&M students who started with Bitcoin mining","A Silicon Valley venture capital firm","A major US utility company"],a:1,e:"Brent Whitehead and Matt Lohstroh started Giga in 2019 as Texas A&M students, using lawn-mowing money to mine Bitcoin. By 2025 they hit $150M+ in revenue and made Forbes 30 Under 30. This origin story builds credibility with customers because the founders understand the products from the user side.",s:U.A},
{q:"What is a dry-type transformer, and when would you recommend one?",o:["A transformer that hasn't been installed yet","Uses air cooling instead of oil — safe for indoor installation","Only works in dry desert climates","A transformer sold without a warranty"],a:1,e:"Instead of being filled with oil, dry-type transformers use air for cooling. This makes them safe to install indoors, like inside hospitals, schools, and office buildings. If a customer needs a transformer inside a building, dry-type is the answer.",s:U.S},
{q:"What does a polemount transformer look like, and where is it installed?",o:["The big green box sitting on the ground","The gray cylinder mounted on a utility pole","A portable generator on wheels","A battery storage unit in a garage"],a:1,e:"Those gray cylinders you see on wooden utility poles in neighborhoods? Those are polemount transformers. They step down the high-voltage overhead power line to 120/240V, which is what comes out of your wall outlets at home.",s:U.S}
],
2:[
{q:"What is the maximum kVA rating for Giga's 3-phase padmount transformer?",o:["1,000 kVA","5,000 kVA","10,000 kVA","25,000 kVA"],a:2,e:"Giga's largest 3-phase padmount handles 10,000 kVA (also written as 10 MVA, since 1 MVA = 1,000 kVA) at up to 46 kV (kilovolts). UL-listed models (meaning independently safety-tested) go up to 8,400 kVA. That's enough power for a large commercial facility.",s:U.S},
{q:"How fast can Giga ship an in-stock transformer from their warehouse?",o:["2-4 weeks","1-2 business days","Within the same month","6-8 weeks"],a:1,e:"In-stock units ship in 1-2 business days from the Long Beach, CA warehouse. In an industry where most companies quote months or years, shipping in days is a game-changer. This is often the stat that makes customers' jaws drop.",s:U.S},
{q:"What is the typical lead time for a custom-built Giga padmount transformer?",o:["6-8 months","52 weeks (1 year)","12-14 weeks (about 3 months)","3-4 weeks"],a:2,e:"Giga builds custom padmounts in 12-14 weeks (about 3 months). The big competitors, ABB, Eaton, and Siemens, take 52-104+ weeks (1-2 years). That speed gap is your strongest selling point.",s:U.S},
{q:"What is the approximate starting price for a 75 kVA 3-phase padmount transformer?",o:["About $10,000","About $32,400","About $55,000","About $80,000"],a:1,e:"A 75 kVA 3-phase padmount (enough for a small commercial building) starts around $32,400. Knowing price points helps you quickly ballpark deals for customers without needing to check a price sheet every time.",s:U.S},
{q:"At what power level should you recommend an MV substation instead of a padmount?",o:["When the customer wants a cheaper option","When they need more than 10 MVA of capacity","When the equipment is going indoors","For residential subdivision use"],a:1,e:"Padmounts max out at 10 MVA (megavolt-amperes). When a customer needs more than that, like for a large industrial park or campus, you move up to a medium-voltage (MV) substation, which handles up to 60 MVA. Knowing this boundary helps you recommend the right product.",s:U.S},
{q:"What primary voltage range do Giga's MV (medium-voltage) substations handle?",o:["120V to 480V","1 kV to 5 kV","5 kV to 35 kV","69 kV to 138 kV"],a:2,e:"MV (medium-voltage) substations handle 5-35 kV on the primary (incoming) side and deliver up to 60 MVA. Think of them as the main power gateway for large facilities like industrial parks, campuses, or big data centers.",s:U.S},
{q:"What does 'DOE 2016 compliant' mean on a transformer spec sheet?",o:["Approved by the Department of Education for school use","Meets U.S. Department of Energy minimum efficiency requirements","Manufactured in 2016 or later","Equipped with a Digital Operating Environment"],a:1,e:"DOE stands for the U.S. Department of Energy. In 2016 they set minimum efficiency standards that all distribution transformers must meet, like fuel economy standards for cars. Giga's transformers are DOE 2016 compliant, which means they meet federal efficiency requirements. Customers sometimes ask about this.",s:U.S},
{q:"What is FR3 transformer fluid, and why would a customer choose it over mineral oil?",o:["A fire retardant spray applied to the exterior","A biodegradable natural ester alternative to mineral oil — safer and eco-friendly","A type of industrial refrigerant","A synthetic motor oil for dry-type units"],a:1,e:"FR3 is a plant-based (soybean) fluid used inside transformers instead of traditional mineral oil. It's biodegradable and has a higher fire point, meaning it's safer and more environmentally friendly. Customers near waterways or in eco-conscious areas often prefer FR3.",s:U.S},
{q:"What warranty does Giga offer on its transformers?",o:["90-day limited warranty","1-year parts only","3-year full warranty against defects, plus free shipping","5-year limited with paid shipping"],a:2,e:"Giga offers a 3-year full warranty against defects, plus free shipping anywhere in the contiguous US. Both are strong selling points. Many competitors charge extra for shipping on heavy equipment like transformers.",s:U.S},
{q:"What is the approximate starting price for a 2,500 kVA padmount transformer?",o:["About $32,000","About $55,000","About $80,000","About $120,000"],a:2,e:"A 2,500 kVA padmount (enough for a medium-sized data center or industrial facility) starts around $80,000. For comparison, the entry-level 75 kVA is about $32,400. Price scales with power capacity, so knowing these anchors helps you size deals quickly.",s:U.S}
],
3:[
{q:"What is the maximum capacity and voltage class of Giga's HV (high-voltage) substations?",o:["10 MVA at 35 kV","60 MVA at 69 kV","100 MVA at up to 138 kV","200 MVA at 230 kV"],a:2,e:"HV (high-voltage) substations handle 69-138 kV and up to 100 MVA. These connect directly to the big transmission lines you see on tall metal towers. They're for the largest projects, like major industrial parks or utility-scale installations.",s:U.S},
{q:"What does a K-Factor rating (e.g., K-13) indicate about a transformer?",o:["The physical weight class of the unit","Its ability to handle harmonic loads from electronic equipment without overheating","The available color options for the enclosure","Its seismic resistance rating for earthquake zones"],a:1,e:"Electronics like computers, LED lights, and variable-speed motors create 'dirty' power (called harmonic distortion). A K-Factor rating (up to K-13) tells you how well a transformer handles that dirty power without overheating. Data centers full of servers need high K-Factor ratings.",s:U.S},
{q:"What does 'UL-listed' mean on Giga's transformer specifications?",o:["Independently safety-tested by Underwriters Laboratories","Ultra-lightweight design certification","Universal Logistics shipping certification","Utility-level power rating"],a:0,e:"UL stands for Underwriters Laboratories, an independent organization that tests products for safety. 'UL-listed' means the equipment passed their testing. Many building codes and inspectors require UL-listed equipment, so it's often a must-have for customers.",s:U.S},
{q:"Which IEEE standard specifically covers the design and testing of power transformers?",o:["IEEE 802.11 (Wi-Fi networking)","IEEE C57 (power transformer design and testing)","IEEE 1547 (distributed energy interconnection)","IEEE 519 (harmonic control)"],a:1,e:"IEEE (Institute of Electrical and Electronics Engineers) publishes industry standards. C57 is the specific standard covering how power transformers should be designed, built, and tested. When an engineer asks 'Is this C57 compliant?', they're asking if it meets the industry's quality benchmark.",s:U.S},
{q:"What is the annual production capacity target for Giga's Houston transformer factory?",o:["500 units/year","1,000 units/year","3,000+ units/year","10,000 units/year"],a:2,e:"The Houston factory is scaling to produce 3,000+ transformers per year, which equals about 15 GW of capacity. They use advanced terahertz drying oven technology to speed up production. For sales context, this means Giga can actually back up its fast lead time promises with real manufacturing capacity.",s:U.F},
{q:"What does a load tap changer do on a substation transformer?",o:["Loads transformers onto delivery trucks","Adjusts voltage output while the transformer is energized and serving customers","Changes the cooling oil during maintenance","Switches between 1-phase and 3-phase operation"],a:1,e:"A load tap changer adjusts the transformer's voltage output while it's running and serving customers. Think of it like cruise control for voltage. As demand goes up and down throughout the day, the tap changer keeps the output steady. Found on larger substations where consistent voltage is critical.",s:U.S},
{q:"What is an amorphous steel core, and why does it matter for transformer efficiency?",o:["A cheaper but weaker core material","A higher-efficiency core that reduces standby energy losses over the transformer's life","A core material that physically changes shape under load","An experimental, unproven technology not yet in production"],a:1,e:"Regular steel has a crystal structure that wastes energy as heat. Amorphous steel has a non-crystalline (glass-like) structure that wastes much less. Transformers with amorphous cores lose less electricity just sitting there, saving the customer money on energy bills over the transformer's 20-30 year life.",s:U.S},
{q:"What does a Buchholz relay detect inside an oil-filled transformer?",o:["Theft or tampering attempts","Internal faults by detecting gas accumulation from overheating or arcing","Overcharging beyond rated capacity","Lightning strikes on the incoming power line"],a:1,e:"A Buchholz relay is a safety device on oil-filled transformers. When something goes wrong inside (like overheating or electrical arcing), it produces gas. The Buchholz relay detects that gas and can automatically shut the transformer down before serious damage occurs. Think of it like a smoke detector for transformers.",s:U.S},
{q:"What does NEC Article 450 cover, and why should a salesperson know about it?",o:["Internet wiring standards for commercial buildings","Grounding, overload protection, and safe transformer installation requirements","Fire escape routing near electrical equipment","Generator fuel storage regulations"],a:1,e:"NEC stands for the National Electrical Code, the rulebook for safe electrical installations in the US. Article 450 specifically covers transformer installation: how to ground them, protect against overloads, and ventilate properly. Engineers and inspectors reference this, so knowing it exists builds credibility.",s:U.S},
{q:"Which major electrical distributors carry Giga transformers?",o:["Home Depot and Lowes","Graybar, Border States, CED, and Rexel","Amazon and Alibaba","Giga sells direct only — no distributors"],a:1,e:"Giga's transformers are carried by major electrical distributors: Graybar, Border States, CED, Rexel, and others. These are the big-name supply houses that electricians and contractors already buy from. Having distribution partners means customers can order through their existing supply relationships.",s:U.S}
]},
switchgear:{
0:[
{q:"What unit is used to measure electrical current flowing through a wire?",o:["Volts","Watts","Amperes (amps)","Ohms"],a:2,e:"Amperes (amps) measure current flow — how much electricity is actually moving. Volts measure pressure, watts measure power consumed, and ohms measure resistance. A wire carrying 200 amps is carrying a LOT of current. Circuit breakers are rated in amps because they need to cut off the flow when it gets dangerously high.",s:U.EE},
{q:"What does 'NEMA' stand for, and why do you see NEMA ratings on electrical enclosures?",o:["National Energy Management Association","National Electrical Manufacturers Association — their ratings define how well an enclosure protects equipment from the environment","New Equipment Manufacturing Approval","No Errors in Manufacturing Assured"],a:1,e:"NEMA = National Electrical Manufacturers Association. Their ratings (NEMA 1, NEMA 3R, NEMA 4, etc.) tell you how much environmental protection an enclosure provides. NEMA 1 = indoor only, basic dust protection. NEMA 3R = outdoor, protects against rain. NEMA 4 = outdoor, protects against rain AND direct water spray. When customers say 'we need NEMA 3R,' they need outdoor-rated equipment.",s:U.EE},
{q:"In electrical terms, what does a 'fault' refer to?",o:["A defect in the wiring insulation","An abnormal current flow, typically from a short circuit","A mistake on an electrical blueprint","A power outage"],a:1,e:"A fault is when current flows where it shouldn't — usually because of a short circuit (two wires touching that shouldn't be). Faults can be massive: thousands of amps surging through equipment in milliseconds. This is why breakers and fuses exist — to interrupt fault current before it melts wires or starts fires. 'Fault current rating' tells you how much a breaker can handle.",s:U.EE},
{q:"What does 'NEC' stand for in the context of electrical installations?",o:["National Energy Commission","New Electrical Components","National Electrical Code — the safety rules for how electrical systems must be installed","Network Equipment Configuration"],a:2,e:"The NEC (National Electrical Code) is the set of rules that governs how electrical equipment must be installed in the US. It covers everything from wire sizes to clearance distances to equipment ratings. Building inspectors enforce it. When you see 'NEC 450' on transformer specs, it means the installation follows Article 450 of the code, which covers transformer safety.",s:U.EE},
{q:"What is the difference between 'single-phase' and 'three-phase' electrical service?",o:["Single-phase costs more than three-phase","Three-phase delivers more power using three coordinated electrical waves — used for commercial and industrial applications","Single-phase is for outdoor use; three-phase is for indoor use","There is no real difference — they are interchangeable"],a:1,e:"Single-phase power uses one wave and is standard for homes (120/240V). Three-phase uses three waves offset by 120 degrees, delivering much more power — it's standard for commercial buildings, factories, and data centers. If a customer runs anything bigger than a house, they almost certainly need three-phase. This is a fundamental concept in power distribution.",s:U.EE},
{q:"What is 'IEEE' and what role does it play in the electrical industry?",o:["A type of electrical connector","Institute of Electrical and Electronics Engineers — they set technical standards for electrical equipment","International Electricity Export Exchange","An electrical safety warning label"],a:1,e:"IEEE (pronounced 'Eye-triple-E') = Institute of Electrical and Electronics Engineers. They publish standards that define how electrical equipment should be designed, tested, and operated. IEEE C57, for example, covers transformer design and testing. When equipment says 'IEEE compliant,' it means it was built and tested to these industry-accepted standards.",s:U.EE},
{q:"What does 'load' mean in electrical engineering?",o:["The physical weight of the equipment","The amount of power being consumed by connected devices and systems","How long it takes to install equipment","The number of wires in a circuit"],a:1,e:"Load = how much power is being drawn by everything connected to the system. If a building's lights, HVAC, and servers are pulling 500 kW total, that's a 500 kW load. Understanding load is critical because all equipment (transformers, switchboards, breakers) must be sized to handle the expected load, plus a safety margin.",s:U.EE},
{q:"What is 'power factor' and why do engineers care about it?",o:["The price per kilowatt of electricity","A measure of how efficiently electrical power is being used (1.0 = perfectly efficient)","The speed at which power travels through a wire","The factor by which you multiply to convert AC to DC"],a:1,e:"Power factor measures efficiency, from 0 to 1.0. A power factor of 1.0 means all the power being delivered is doing useful work. A lower power factor means some power is being wasted as heat. Utilities sometimes charge penalties for poor power factor. This is why kVA (total capacity) and kW (actual useful power) are different numbers — the gap between them is the power factor.",s:U.EE}
],
1:[
{q:"What is the primary function of a switchboard in a power distribution system?",o:["Generates electricity from a fuel source","Distributes power from a transformer to multiple circuits with breaker protection","Stores electricity in batteries for backup","Converts DC power to AC power"],a:1,e:"Think of a switchboard like the fuse box in your house, but industrial-sized. A transformer delivers power to the building, and the switchboard splits it into separate circuits (one for each area or piece of equipment) with circuit breakers that shut off if something goes wrong.",s:U.S},
{q:"Which specific UL standard does Giga's switchboard product carry?",o:["UL 67 (Panelboard)","UL 891 (Low Voltage Switchboard)","UL 1558 (MV Switchgear)","All of the above"],a:1,e:"Giga builds UL 891 switchboards. UL 891 is the safety standard for low-voltage switchboards (under 600V). This is Giga's only switchgear product, and it covers the vast majority of commercial and industrial applications. Simple to remember: one product, one standard.",s:U.S},
{q:"In which city are Giga's switchboards manufactured?",o:["Houston, TX","Long Beach, CA","Shanghai, China","Mumbai, India"],a:1,e:"Switchboards are built in Long Beach, CA (near LA). Transformers are made in Houston, TX. Knowing which factory makes what helps when customers ask about shipping timelines or want to visit a facility.",s:U.S},
{q:"Approximately how many switchboards has Giga built to date?",o:["About 50","200+","1,000+","5,000+"],a:1,e:"Giga has built over 200 switchboards so far, plus 1,000+ transformers and 750+ data centers. These numbers show customers that Giga isn't a startup experimenting. They have a real track record across the full product line.",s:U.A},
{q:"What is the maximum amperage rating for Giga's 480V switchboard?",o:["800A","2,000A","4,000A","10,000A"],a:2,e:"Up to 4,000 amps at 480 volts. Amps measure how much electrical current flows through, like gallons per minute in a pipe. 4,000A is a lot of current, enough for a large data center. They also offer 600V up to 2,000A, with 800V coming soon.",s:U.S},
{q:"What is Giga's standard lead time for a switchboard delivery?",o:["2-4 weeks","8-12 weeks standard, 7 weeks expedited","20-30 weeks","52+ weeks"],a:1,e:"Giga delivers switchboards in 8-12 weeks standard or 7 weeks expedited. The major competitors (Eaton, Schneider, Siemens) take 20-52+ weeks. Same speed advantage story as transformers, and just as powerful in sales conversations.",s:U.S},
{q:"What brand of circuit breaker comes standard in Giga switchboards?",o:["Siemens","Eaton","ABB","Square D"],a:2,e:"ABB is a major global brand for circuit breakers. Giga uses ABB breakers as standard equipment, with up to 12 per cabinet. Using a trusted brand like ABB gives customers confidence in the quality of what's inside the switchboard.",s:U.S},
{q:"Why is a switchboard critical for data center power delivery?",o:["It makes the facility look more professional","It distributes transformer power safely to individual server racks with breaker protection","It generates backup power during outages","It cools server racks with built-in fans"],a:1,e:"In a data center, the transformer brings power in and the switchboard splits it out to all the server racks safely, with breaker protection on every circuit. Without a switchboard, there's no safe way to get power from one big source to hundreds of individual machines.",s:U.S},
{q:"What is the approximate base price for a Giga switchboard?",o:["About $15,000","About $45,000","About $90,000","About $200,000"],a:2,e:"Base price starts around $90,000 for a standard switchboard. The great news for sales: adding customizations like surge protection or metering does not extend the lead time. Customers get exactly what they need without waiting longer.",s:U.S},
{q:"In a power distribution system, what is the relationship between a transformer and a switchboard?",o:["The switchboard replaces the transformer","The transformer feeds power to the switchboard, which distributes it to individual circuits","The switchboard powers the transformer","They serve completely different, unrelated purposes"],a:1,e:"Power flows in order: Grid sends power to the Transformer (which steps voltage down), then to the Switchboard (which distributes it to individual circuits). Giga can sell both together, pre-wired on a single platform called a skid. One delivery, one vendor, less hassle for the customer.",s:U.S}
],
2:[
{q:"What KAIC (fault current interrupting) ratings does Giga offer for its switchboards?",o:["25 or 50 KAIC","65 or 100 KAIC","100 or 200 KAIC","Only 65 KAIC"],a:1,e:"KAIC stands for Kilo Ampere Interrupting Capacity. It measures how much fault current (a short circuit surge) a breaker can safely stop. Think of it like how big of a car crash a guardrail can handle. Giga offers 65 and 100 KAIC. Higher-power sites like data centers usually need 100 KAIC.",s:U.S},
{q:"What NEMA enclosure ratings are available for Giga switchboards?",o:["NEMA 1 (indoor) or NEMA 3R (outdoor rain/ice-rated)","NEMA 4X only (heavy washdown)","NEMA 12 only (dust-tight)","No NEMA rating available"],a:0,e:"NEMA (National Electrical Manufacturers Association) rates how well an enclosure protects equipment. NEMA 1 = basic indoor protection (dust). NEMA 3R = outdoor-rated, protecting against rain, sleet, and ice. When a customer's switchboard will be outside, you need 3R.",s:U.S},
{q:"What is the fastest possible (expedited) lead time for a Giga switchboard?",o:["Same day shipping","3-4 weeks","7 weeks","12 weeks"],a:2,e:"Giga can push a switchboard out in as fast as 7 weeks on an expedited timeline, compared to the standard 8-12 weeks. For a customer with an urgent deadline, shaving off a month can make or break their project schedule.",s:U.S},
{q:"How do Giga's switchboard lead times compare to Eaton, Schneider, and Siemens?",o:["About the same across all vendors","Slightly faster by a few weeks","Much faster: Giga 8-12 weeks vs. competitors' 20-52+ weeks","Slightly slower than the major brands"],a:2,e:"Giga: 8-12 weeks. Eaton, Schneider, Siemens: 20-52+ weeks. That's potentially getting equipment 6-10 months sooner. For customers with construction deadlines, delayed equipment means delayed revenue. This speed gap is your #1 talking point.",s:U.S},
{q:"Does adding surge protection, metering, or other customizations to a Giga switchboard extend the lead time?",o:["Yes, each customization adds 4-6 weeks","No — all customizations stay within the standard 8-12 week lead time","Only on expedited orders","Those customizations are not available"],a:1,e:"Adding extras like surge protection, power metering, ground fault detection, or CTs/VTs (current/voltage monitoring devices) does NOT add time. Everything stays within the 8-12 week window. This is a big deal because competitors often add weeks for customization.",s:U.S},
{q:"What new voltage option is Giga adding to its switchboard product line?",o:["240V for residential use","600V (already available)","800V for next-generation data centers","1,200V for industrial applications"],a:2,e:"Giga currently offers 480V (up to 4,000A) and 600V (up to 2,000A). An 800V option is coming soon, which will serve next-generation data centers that need higher voltage for efficiency. Knowing the product roadmap helps you have forward-looking conversations with customers.",s:U.S},
{q:"What is a skid-mounted system, and why do customers prefer it?",o:["A system mounted on wheels for portability","A transformer + switchboard pre-wired on one steel base, factory-tested before delivery","A temporary installation meant to be removed later","A specialized cooling system for outdoor equipment"],a:1,e:"A skid-mounted system puts the transformer and switchboard together on one steel base, pre-wired and factory-tested before it leaves the building. The customer gets one delivery instead of coordinating two separate pieces. Less installation hassle, less risk of field wiring errors.",s:U.S},
{q:"How many ABB circuit breakers can fit in a single Giga switchboard cabinet?",o:["Up to 4","Up to 8","Up to 12","Up to 24"],a:2,e:"Each switchboard cabinet holds up to 12 ABB breakers, and you can connect multiple cabinets together for larger installations. This modular approach means the system can scale with the customer's needs without replacing the whole thing.",s:U.S}
],
3:[
{q:"What is the key difference between UL 891 (what Giga builds) and UL 1558?",o:["UL 891 is the newer standard","UL 891 covers low-voltage switchboards; UL 1558 covers medium-voltage switchgear","They are interchangeable standards","UL 891 is only for outdoor installations"],a:1,e:"UL 891 covers low-voltage switchboards (up to 600V), which is what Giga builds. UL 1558 covers medium-voltage switchgear (above 600V), which Giga does not make. If a customer needs medium-voltage switchgear, that's a different product category. Knowing this boundary prevents awkward conversations.",s:U.S},
{q:"What does KAIC stand for, and what does it measure?",o:["Kilo Ampere Interrupting Capacity — the max fault current a breaker can safely stop","Kilowatt Ampere Internal Circuit — total power throughput","Known Average Input Current — the normal operating load","Key Automatic Isolation Control — an emergency shutdown rating"],a:0,e:"KAIC = Kilo Ampere Interrupting Capacity. It's the maximum surge of electricity (from a short circuit or fault) that a breaker can safely cut off without damage. The higher the KAIC rating, the bigger the 'electrical emergency' the breaker can handle. Data centers need high ratings because they concentrate so much power.",s:U.S},
{q:"Why do data centers specifically need 100 KAIC breakers instead of the lower 65 KAIC option?",o:["Data centers have low fault current, so either works","Data centers concentrate massive power in small spaces, creating high potential fault currents","100 KAIC is just a marketing feature with no practical difference","100 KAIC reduces fan noise in the facility"],a:1,e:"Data centers pack huge amounts of power into small spaces, which means if something short-circuits, the fault current (electrical surge) can be massive. 100 KAIC means the breakers can handle even the worst-case scenario. For sales, if someone's building a data center, always recommend 100 KAIC.",s:U.S},
{q:"What is the 'vertical integration' advantage of buying both transformer and switchboard from Giga?",o:["Just a 10% bundle price discount","Single vendor, pre-wired on one skid, factory-tested together, one delivery, one point of contact","They come in matching paint colors","No real advantage — it's the same as buying separately from different vendors"],a:1,e:"Buying both transformer and switchboard from Giga means one engineering team, one set of drawings, pre-wired delivery on a single skid, and factory testing before it ships. If anything goes wrong, there's one company to call instead of two vendors pointing fingers at each other.",s:U.S},
{q:"What are Giga's current switchboard voltage and amperage options?",o:["208V and 240V only","480V (up to 4,000A) and 600V (up to 2,000A)","480V only, with no other options","Up to 4,160V for medium-voltage applications"],a:1,e:"Currently two voltage options: 480V (handles up to 4,000A, the most common for US commercial/industrial) and 600V (up to 2,000A, used in some Canadian and heavy industrial applications). 800V is on the roadmap for next-generation data center power delivery.",s:U.S},
{q:"What is a CT (current transformer) used for inside a switchboard?",o:["Cooling the internal components","Measuring current flow for metering, monitoring, and protection systems","Converting DC power to AC power","Storing energy during low-demand periods"],a:1,e:"A CT (current transformer) is a small device that measures how much electricity is flowing through a wire. It works by stepping down dangerously high currents to safe, measurable levels. Think of it like a speedometer for electricity. CTs enable metering, monitoring, and protection inside the switchboard.",s:U.S}
]},
datacenters:{
0:[
{q:"What is a data center, in simple terms?",o:["A corporate headquarters building","A building full of computers (servers) that store data and run applications","A power plant that generates electricity","A warehouse for electrical equipment"],a:1,e:"A data center is a purpose-built facility packed with servers — the computers that power everything from Google searches to Netflix streams to AI models. They need enormous amounts of power (for the servers) and cooling (to prevent overheating). Every time you use the internet, a data center is doing the work behind the scenes.",s:U.EE},
{q:"Why do data centers need so much electrical power?",o:["To power the lights in the building","To run thousands of servers AND the cooling systems that keep them from overheating","To charge the electric vehicles in the parking lot","To power the surrounding neighborhood"],a:1,e:"Servers generate intense heat. A modern data center might use 50% of its power just for cooling. A 100 MW data center might have 50 MW of servers and 50 MW of cooling. This is why power infrastructure (transformers, switchboards, cooling systems) is so critical — and why companies like Giga exist.",s:U.EE},
{q:"What does 'uptime' mean in the data center industry?",o:["The time it takes to build a data center","The percentage of time a data center is operational and available — 99.999% is the gold standard","How fast the internet connection is","The hours employees work each day"],a:1,e:"Uptime is the percentage of time a facility stays running without interruption. '99.999%' (called 'five nines') means less than 5 minutes of downtime per year. Large customers like banks and cloud providers REQUIRE extreme uptime because a single hour of downtime can cost millions. This is why data centers have redundant power, cooling, and networking.",s:U.EE},
{q:"What does 'kW per rack' measure in a data center?",o:["The cost of each server rack","How much power each server rack consumes","The physical weight of each rack","The internet speed per rack"],a:1,e:"kW per rack is how the industry measures power density — how much power each individual server rack draws. Traditional servers use 5-10 kW per rack. AI GPU servers use 40-165+ kW per rack. Higher density means more power AND more heat in the same space, which requires specialized infrastructure like liquid cooling.",s:U.EE},
{q:"What are the two main approaches to cooling a data center?",o:["Opening windows and using desk fans","Air cooling (fans and filters) and liquid cooling (pumping coolant through the system)","Putting it underground and putting it underwater","Using ice blocks and refrigerant gas"],a:1,e:"Air cooling blows cool air over the servers using fans and air handling units. It's simpler and cheaper but struggles in hot climates and with high-density AI racks. Liquid cooling pumps coolant directly to the heat sources, handling much higher thermal loads. As AI pushes power density higher, the industry is shifting toward liquid cooling.",s:U.EE},
{q:"What is 'redundancy' in data center design?",o:["Having extra staff on shift","Building backup systems so that if one component fails, another takes over immediately","Using the same brand for all equipment","Having redundant paperwork"],a:1,e:"Redundancy means having backup everything. N+1 means one extra beyond what you need (3 pumps when 2 would suffice). 2N means a complete duplicate of the entire system. Data center customers obsess over redundancy because one equipment failure should never take down the whole facility. This concept applies to power, cooling, networking, and generators.",s:U.EE},
{q:"What is 'PUE' and why is it important for data centers?",o:["Power Usage Effectiveness — measures how efficiently a data center uses power (1.0 is perfect)","Price per Unit of Energy","Power Utility Equipment — a type of generator","Primary Usage Estimate — a projection of future power needs"],a:0,e:"PUE = Power Usage Effectiveness. It's calculated as total facility power divided by IT equipment power. A PUE of 2.0 means for every watt running servers, another watt goes to cooling and overhead. A PUE of 1.2 means very efficient. The industry average is about 1.58. Lower PUE = less wasted energy = lower operating costs. Customers care deeply about this number.",s:U.EE},
{q:"What is 'edge computing' and how does it differ from traditional data centers?",o:["Computing done at the edge of a desk","Small computing facilities located close to users to reduce latency, instead of one large central data center","A brand of laptop computers","Computing that only works at the edge of the network coverage area"],a:1,e:"Instead of sending all data to a massive central data center (which introduces delay), edge computing puts smaller facilities closer to where data is generated and consumed. Think: a small data center in a rural town serving local users rather than routing everything to a faraway hub. This is a growing market for modular data center products like Giga's containers.",s:U.EE}
],
1:[
{q:"What is a modular data center, and how does it differ from a traditional one?",o:["A room filled with servers inside an office building","A pre-built, container-sized unit that arrives ready to plug into power — much faster to deploy","A software application for managing servers remotely","A specialized type of power transformer"],a:1,e:"Think of a shipping container filled with computers instead of cargo. A modular data center is a pre-built, self-contained unit that arrives ready to go. You drop it on site, plug in power, and start computing. Way faster than building a traditional brick-and-mortar data center from scratch.",s:U.AR},
{q:"What are the three types of Giga Box data center products?",o:["Small, Medium, Large","Air (fan-cooled), Hydro (liquid-cooled), HPC (AI/GPU-optimized)","Bronze, Silver, Gold service tiers","Basic, Pro, Enterprise configurations"],a:1,e:"Three products, three use cases. Air: cooled by fans, mainly for Bitcoin mining. Hydro: liquid-cooled for higher-density setups that generate more heat. HPC (High Performance Computing): custom-built for AI and GPU workloads. Knowing which one fits a customer's needs is key to your pitch.",s:U.AR},
{q:"How does the Giga Box Air cool the equipment inside?",o:["Liquid coolant circulating through pipes","Fans blowing ambient air through filters — no water or refrigerant needed","Built-in refrigeration units like an AC system","Geothermal underground cooling loops"],a:1,e:"The Giga Box Air uses big exhaust fans to pull outside air through filters, cooling the equipment inside. No water, no refrigerant, no plumbing needed. Simple and reliable. This makes it cheaper and faster to deploy than liquid-cooled options.",s:U.AR},
{q:"Approximately how many data centers has Giga built to date?",o:["About 100","250+","750+","2,000+"],a:2,e:"Giga has built over 750 data centers, with 175 MW (megawatts) running across 15 sites and 500+ MW in the pipeline. To put 175 MW in perspective, that's enough electricity to power about 130,000 homes. This scale proves Giga knows what they're doing.",s:U.A},
{q:"What type of computing equipment goes inside a Giga Box Air?",o:["Standard office furniture and workstations","Bitcoin mining machines called ASICs (specialized computing chips)","Solar panel inverters","Power transformers for voltage conversion"],a:1,e:"Bitcoin mining machines called ASICs (Application-Specific Integrated Circuits), which are specialized computers built only for mining Bitcoin. The large 40-foot Giga Box Air fits up to 360 of these machines. When customers say 'miners,' they mean these specialized computers, not people with pickaxes.",s:U.AR},
{q:"What is the key difference between the Giga Box Air and the Giga Box Hydro?",o:["The Hydro operates underwater","The Hydro uses liquid cooling instead of air fans — handles more heat and denser equipment","The Hydro is physically smaller","The Hydro costs less than the Air"],a:1,e:"Instead of blowing air, the Hydro uses a closed loop of liquid coolant (like a car's radiator system) to absorb heat from the equipment. This handles much more heat than air cooling, allowing denser equipment packing. It works in temperatures up to 113°F, making it ideal for hot climates like Texas.",s:U.HY},
{q:"What does HPC stand for in Giga's product line, and what is it designed for?",o:["High Power Cooling — industrial refrigeration systems","Hybrid Power Container — combined solar and battery storage","High Performance Computing — AI workloads running on GPUs","Hosted Private Cloud — managed web hosting services"],a:2,e:"HPC = High Performance Computing. These are for AI workloads running on GPUs (graphics processing units, the same chips in gaming computers but used for AI training). HPC data centers need way more power and cooling per rack than crypto mining. This is the premium, high-margin product line.",s:U.AI},
{q:"What is the typical lead time for a Giga Box Air data center?",o:["2-4 weeks","8-12 weeks","6 months","Over a year"],a:1,e:"The Giga Box Air takes 8-12 weeks to build to order, with in-stock units sometimes available in Long Beach, CA. Compare that to building a traditional data center which takes 2-3 years. This speed is what makes modular data centers so attractive to customers.",s:U.AR},
{q:"How fast can Giga deploy a complete, operational data center site compared to the industry standard?",o:["About the same timeline as competitors","Twice as fast (12 months vs. 24)","6-8 months vs. the industry's 24-36+ months","10x faster (3 months vs. 30)"],a:2,e:"Giga can take a project from bare land to fully operational AI-ready data center in 6-8 months. The industry standard is 24-36+ months (2-3 years). In the AI boom, where companies are racing to deploy GPU compute, this speed advantage is worth millions to customers.",s:U.SD},
{q:"Which industries does Giga serve with its data center products?",o:["Only Bitcoin mining operations","Only AI and machine learning companies","Bitcoin mining, AI/HPC, oil & gas, and other industries needing fast compute","Only electric utility companies"],a:2,e:"Bitcoin mining is the core market, but Giga also serves AI/HPC (High Performance Computing), oil and gas (using wasted gas flares to power mining), and anyone else who needs fast computing deployment. For sales, this means you're not limited to one industry when prospecting.",s:U.A}
],
2:[
{q:"What are the two size options for the Giga Box Air, and how much power does each handle?",o:["10-foot and 20-foot models","M Series (20', 600 kW) and L Series (40', 1,430 kW)","40-foot and 53-foot models","Only one size is available"],a:1,e:"Two sizes: M Series is 20 feet long (like a small shipping container), handles 600 kW (kilowatts) of power, and fits 144 mining machines. L Series is 40 feet (full shipping container size), handles 1,430 kW, and fits 360 miners. Most customers want the L for better economics per unit.",s:U.AR},
{q:"What monitoring system does the Giga Box Hydro use to track coolant and temperature?",o:["No monitoring system included","A basic wall-mounted thermometer","A Siemens PLC with a 15-inch HMI touchscreen display","A smartphone app connected via Bluetooth"],a:2,e:"The Hydro uses a Siemens PLC (Programmable Logic Controller, basically an industrial computer) with a 15-inch touchscreen display called an HMI (Human Machine Interface). This lets operators monitor coolant flow, pH levels, pressure, and temperature in real time. Siemens is a trusted brand name that customers respect.",s:U.HY},
{q:"What does 'N+1 redundant pumps' mean in the Giga Box Hydro's cooling system?",o:["A single heavy-duty pump handles everything","One extra backup pump beyond what's needed — if one fails, the backup takes over automatically","A manual backup pump that requires human intervention","No pumps needed — the system uses gravity"],a:1,e:"N+1 means 'one more than you need.' If the system needs 2 pumps to run, it has 3 installed. If one fails, the backup kicks in automatically with no downtime. This is a big selling point because data center customers care deeply about reliability. The Hydro also has an auxiliary pressure pump for extra safety.",s:U.HY},
{q:"What is the maximum outdoor operating temperature for the Giga Box Hydro?",o:["85°F (30°C)","95°F (35°C)","113°F (45°C)","130°F (55°C)"],a:2,e:"The Hydro keeps working in temperatures up to 45°C (113°F). That's hotter than the hottest days in Phoenix or Dubai. Air-cooled systems struggle in extreme heat because the air itself is too hot to cool effectively. This makes the Hydro the right choice for hot-climate customers.",s:U.HY},
{q:"How much power per rack do modern AI GPU servers typically require?",o:["5-10 kW per rack (same as traditional servers)","30-50 kW per rack","165+ kW per rack (roughly 20x more than traditional servers)","500 kW per rack"],a:2,e:"A traditional server rack uses 5-10 kW (kilowatts) of power. Modern AI GPU racks need 165+ kW per rack. That's roughly 20x more power and heat in the same physical space. This is why AI customers need specialized HPC infrastructure, not off-the-shelf data centers.",s:U.BA},
{q:"What is the lead time for a Giga Box Hydro data center?",o:["4-6 weeks","8-12 weeks (same as Air)","12-16 weeks, always built to order","24+ weeks"],a:2,e:"The Hydro takes 12-16 weeks, always built to order (no in-stock units). It's a few weeks longer than the Air because liquid cooling systems need more complex assembly and testing. Still far faster than a traditional data center build.",s:U.HY},
{q:"How many racks does a single Giga HPC pod contain, and how are they configured?",o:["8 racks total","16 racks, all GPU compute","26 racks: 16 GPU compute + 10 networking/storage","48 racks in a double-wide container"],a:2,e:"Each HPC pod holds 26 racks: 16 for GPU compute (the AI processing power) and 10 for networking and storage equipment. They use in-row cooling (cooling units between the racks) and overhead bus bar power (electricity delivered from above, not under the floor). This design maximizes density and airflow.",s:U.BA},
{q:"What is the key difference in the sales process for Giga Box Air/Hydro vs. HPC products?",o:["HPC is cheaper, so it sells faster","Air/Hydro are standard catalog products; HPC is a consultative, custom-engineered sale","HPC ships faster than Air/Hydro","There's no difference in the sales approach"],a:1,e:"Air and Hydro boxes are catalog products with standard specs that you can quote quickly. HPC is a completely different sales process: custom-engineered for each customer based on their GPU type, rack density, and cooling requirements. HPC deals are bigger and more consultative, more like enterprise selling.",s:U.AI}
],
3:[
{q:"What does N+1 redundancy mean, and why do enterprise data center customers require it?",o:["A nice-to-have feature that saves money on utilities","One extra backup component for every critical system — because data center downtime costs millions per hour","A networking protocol for server communication","A government regulation for all electrical installations"],a:1,e:"N+1 redundancy means for every N components needed to run, you install N+1 (one extra). If you need 3 cooling units, you install 4. Enterprise customers require this because downtime at a large data center can cost millions per hour. It's not optional for serious buyers.",s:U.HY},
{q:"What is the complete Giga power delivery chain from utility to end-use?",o:["Utility → Computer (direct connection)","Utility → Transformer → DC converter → Battery","Utility → Transformer → Switchboard → Data Center → GPS energy optimization","Utility → Switchboard → Transformer → Data Center"],a:2,e:"The full chain: Utility power comes in, the Transformer steps voltage down, the Switchboard distributes it, the Data Center uses it for computing, and GPS software optimizes energy costs. Giga builds every single piece of this chain. No other company does that. This 'vertical integration' is a massive competitive advantage.",s:U.SD},
{q:"What are the four steps of Giga's site development process, and how long does it take total?",o:["Plan, Build, Test, Ship (12 months)","Assess & Partner → Design & Manufacture → Construct & Connect → Operate & Monitor (6-8 months total)","Survey, Quote, Build, Invoice (4 months)","Research, Develop, Deploy, Maintain (18 months)"],a:1,e:"The four steps are: (1) Assess and Partner (Month 1, evaluate the site and customer needs), (2) Design and Manufacture (Months 2-5, engineer and build equipment), (3) Construct and Connect (Months 4-6, install on site), (4) Operate and Monitor (ongoing 24/7 management). Steps overlap, which is how they compress a 3-year process into 6-8 months.",s:U.SD},
{q:"How many megawatts of data center capacity does Giga currently operate?",o:["25 MW across 5 sites","75 MW across 10 sites","175 MW across 15 sites, with 500+ MW in the pipeline","500 MW across 50 sites"],a:2,e:"Giga operates 175 MW (megawatts) of data centers across 15 sites, with over 500 MW planned. For context, 175 MW could power a small city. The pipeline being 3x current capacity shows rapid growth, which matters in sales because customers want to work with a company that's scaling, not shrinking.",s:U.A},
{q:"Which four US power grid regions does Giga currently operate in?",o:["ERCOT (Texas) only","ERCOT (Texas) and SPP (14 central states)","ERCOT (Texas), SPP (14 central states), MISO (15 midwest states), PJM (13 eastern states)","All US grid regions"],a:2,e:"Giga operates in four US power grid regions: ERCOT (Texas, independent grid), SPP (Southwest Power Pool, 14 central states), MISO (Midcontinent, 15 midwest states), and PJM (13 eastern states, the biggest data center corridor in the world). Each region is run by a different grid operator with different rules and pricing.",s:U.G},
{q:"What is the minimum project size for Giga's full site development service?",o:["1 MW — they take all sizes","5 MW for standard projects","Approximately 10 MW, evaluated case by case","50 MW minimum"],a:2,e:"Giga's full site development service starts at roughly 10 MW minimum, evaluated case by case. Customers with smaller power needs can buy standalone Giga Box products instead. Knowing this threshold helps you route customers to the right sales track.",s:U.SD},
{q:"Why is Giga's operational experience (running their own sites) a sales advantage?",o:["It's not relevant to customer conversations","It qualifies them for volume discounts from suppliers","They use the same equipment and playbooks on their own 175 MW of sites that they sell to customers","They have more employees than competitors"],a:2,e:"Giga runs 175 MW of their own data center sites using the exact same equipment they sell to customers. This 'eating their own cooking' means they've pressure-tested everything in real-world conditions. In sales, this is powerful: 'We don't just sell it, we run on it ourselves.'",s:U.A}
]},
gps:{
0:[
{q:"What is a 'wholesale energy market'?",o:["A store where you buy light bulbs in bulk","A marketplace where electricity is bought and sold in large quantities before reaching consumers","A wholesale warehouse for solar panels","A government agency that distributes energy"],a:1,e:"Wholesale energy markets are where power generators sell electricity and utilities/large consumers buy it. Prices change every few minutes based on supply and demand — just like a stock market, but for electricity. When demand is high (hot summer afternoon), prices spike. When supply exceeds demand (windy night), prices can even go negative. Smart operators profit from these swings.",s:U.EE},
{q:"What is 'energy arbitrage'?",o:["Stealing electricity from neighbors","Buying electricity when it's cheap and selling it (or using it) when it's expensive","Converting energy from one form to another","Arbitrating disputes between energy companies"],a:1,e:"Energy arbitrage means consuming power when prices are low and curtailing (reducing usage) when prices are high. For a Bitcoin mine or flexible data center, this means: run your servers when electricity is $20/MWh, shut down when it spikes to $200/MWh, and get paid for the flexibility. The profit is in the price spread.",s:U.GP},
{q:"What is an 'ISO' or 'RTO' in the energy industry?",o:["International Standards Organization — they certify equipment","Independent System Operator / Regional Transmission Organization — they manage the power grid and energy markets","A type of backup generator","Internet Service Operator — they provide internet to data centers"],a:1,e:"ISOs and RTOs are organizations that operate the power grid and run the wholesale electricity markets for their region. ERCOT manages Texas. SPP covers Oklahoma, Kansas, and surrounding states. PJM covers the Mid-Atlantic and part of the Midwest (the largest US electricity market). MISO covers the central US. Each has its own rules, markets, and opportunities.",s:U.GR},
{q:"What is 'ancillary services' in energy markets?",o:["Extra customer service provided by utility companies","Services that help keep the grid stable — like having power ready to ramp up or down on short notice","Maintenance services for power lines","Administrative support for energy companies"],a:1,e:"Ancillary services are products that help the grid operator keep the system stable and balanced. Examples: frequency regulation (adjusting power output moment-to-moment to keep the grid at 60 Hz), spinning reserves (having generators ready to ramp up within minutes), and voltage support. These services pay well because reliability is critical. Flexible loads like data centers can provide these services.",s:U.GP},
{q:"What is a 'capacity payment' in the energy market?",o:["The amount you pay for a battery","Money paid to power producers or large consumers just for being AVAILABLE to supply or reduce power when needed","A one-time installation fee for new equipment","The capacity of a transformer in kVA"],a:1,e:"Capacity payments are money you get paid just for being available — you don't even have to generate or reduce power, just promise that you CAN. Grid operators pay capacity payments to ensure there's enough power available during peak periods. It's like getting paid to be on standby. This is one of the four revenue streams GPS helps customers capture.",s:U.GP},
{q:"What does 'behind the meter' mean in energy?",o:["Equipment installed behind the electric meter — on the customer's side, not the utility's side","A secret energy source","Equipment that's too small to meter","Power generated underground"],a:0,e:"'Behind the meter' means on the customer's side of the electricity meter — inside their property. Equipment 'in front of the meter' is on the utility's side. This distinction matters because behind-the-meter assets (like a data center's generators or batteries) can participate in energy markets differently than utility-scale power plants. Giga's customers operate behind the meter.",s:U.EE},
{q:"What does 'curtailment' mean in the energy industry?",o:["Installing curtains in a data center for privacy","Deliberately reducing power consumption or generation in response to grid conditions or prices","Cutting power lines during emergencies","Reducing the size of a power plant"],a:1,e:"Curtailment means intentionally dialing back. A wind farm might curtail (reduce output) when there's too much wind power on the grid. A Bitcoin mine might curtail (shut down miners) when electricity prices spike. The ability to curtail quickly is valuable because grid operators will pay you for that flexibility.",s:U.GP},
{q:"Why does renewable energy (wind and solar) create price volatility in electricity markets?",o:["Renewable energy is always expensive","Wind and solar output is unpredictable — when it's windy/sunny, prices drop; when it's not, prices spike","Renewable energy uses more fuel","Solar panels are fragile and break often"],a:1,e:"Wind and solar can't be turned on and off like a gas plant. When the wind blows hard, the grid is flooded with cheap power (prices drop, sometimes to zero or negative). When the wind dies and clouds roll in, supply drops and prices spike. This volatility creates huge opportunities for flexible loads that can shift their consumption around price swings — which is exactly what GPS helps customers do.",s:U.BS}
],
1:[
{q:"In Giga's product line, what does 'GPS' stand for?",o:["Global Positioning System (satellite navigation)","Giga Power Systems (energy optimization software platform)","General Power Supply (backup generators)","Grid Protection Service (cybersecurity)"],a:1,e:"GPS stands for Giga Power Systems (not the satellite navigation kind). It's a software platform that helps data center operators make money from wholesale energy markets. Launched January 13, 2026. This is Giga's newest product and a major growth area.",s:U.G},
{q:"What is 'demand response,' and how do data center operators make money from it?",o:["Demanding faster service from the electric utility","Getting paid to reduce electricity usage when the power grid is stressed","Responding to customer product demands more quickly","A type of electrical resistance measurement"],a:1,e:"Demand response is getting paid to use LESS electricity when the power grid is stressed (like on a scorching summer afternoon when everyone blasts AC). Instead of the grid firing up expensive backup power plants, they pay big electricity users to temporarily cut back. It's like getting paid to skip dinner when the restaurant is overcrowded.",s:U.G},
{q:"Why are Bitcoin mining data centers ideal candidates for demand response programs?",o:["They use very little power compared to other facilities","They can shut down temporarily without critical consequences — unlike hospitals or factories","They have built-in backup generators","They are always located near power plants"],a:1,e:"Bitcoin miners and batch AI workloads can pause or shut down temporarily without real consequences, unlike a hospital or factory. That makes them the grid's dream 'flexible load.' When the grid says 'please use less power,' a data center can flip a switch. A hospital can't. That flexibility is worth real money.",s:U.G},
{q:"How much revenue can GPS generate per megawatt per year for a data center operator?",o:["About $5,000/MW/year","About $20,000/MW/year (same as generic programs)","$50,000 to $80,000/MW/year","Over $200,000/MW/year"],a:2,e:"GPS generates $50,000-$80,000 per megawatt per year by participating in multiple energy markets simultaneously. Generic demand response programs only get about $20,000/MW/year. That's a 2.5-4x improvement. For a 50 MW facility, the difference is millions of dollars annually.",s:U.BR},
{q:"Which US power grid market did GPS launch in first, and why?",o:["ERCOT (Texas) — largest market","PJM (eastern US) — most data centers","SPP (Southwest Power Pool) — shrinking reserves and wind-driven price swings","MISO (Midwest) — cheapest electricity"],a:2,e:"GPS launched in SPP (Southwest Power Pool), which manages the power grid across 14 central US states. SPP was chosen because its reserve margins (backup power capacity) are shrinking, it has lots of wind energy creating price swings, and the grid actively wants flexible loads. All of that means more revenue opportunity for GPS customers.",s:U.GP},
{q:"What does 'flexible load' mean in the context of energy markets?",o:["Equipment that physically bends or is portable","Any electricity user that can increase or decrease power consumption on demand","A type of payment plan for utility bills","A circuit breaker that adjusts automatically"],a:1,e:"A 'flexible load' is any electricity user that can dial power up or down on command based on grid conditions. Bitcoin miners are the perfect example because they can shut off instantly with no damage to the work. A factory making car parts? Not flexible. A Bitcoin mine? Very flexible. GPS monetizes that flexibility.",s:U.G},
{q:"How does GPS differ from a generic demand response provider?",o:["No meaningful difference — they do the same thing","GPS optimizes hour-by-hour using computing economics, not daily/weekly averages, and pays faster","GPS just charges more for the same service","GPS only works in Texas"],a:1,e:"Generic demand response programs make simple on/off decisions on daily or weekly schedules. GPS optimizes hour by hour, factoring in Bitcoin mining profitability and electricity prices, to decide when to run and when to curtail. Plus, GPS pays out in 30-45 days vs 60-90 days with generic providers. Faster money is better money.",s:U.G},
{q:"When did Giga Power Systems (GPS) officially launch?",o:["2019 (when Giga was founded)","2024","January 13, 2026","It hasn't launched yet"],a:2,e:"GPS officially launched January 13, 2026 in the SPP (Southwest Power Pool) market. Expansion to ERCOT (Texas), PJM (eastern US), and MISO (midwest) is planned. Being brand-new means there's ground-floor energy in the sales team and lots of market to capture.",s:U.GP},
{q:"How does a GPS software contract create sales opportunities for Giga hardware?",o:["It doesn't — software and hardware are separate divisions","Multi-year GPS contracts unlock rebates on Giga hardware purchases (transformers, switchboards, data centers)","GPS replaces the need for Giga hardware entirely","It's software-only with no hardware connection"],a:1,e:"Here's the sales magic: customers who sign multi-year GPS contracts can get rebates on Giga hardware (transformers, switchboards, data centers). This creates 'stickiness,' meaning once they're in the GPS ecosystem, they keep buying Giga products. Every transformer customer running flexible load is a GPS prospect too.",s:U.G},
{q:"What is 'energy arbitrage,' and how does it generate profit for data center operators?",o:["Buying energy company stocks low and selling high","Running operations when electricity is cheap and shutting down when it's expensive — pocketing the difference","Selling excess solar panel energy back to the grid","Trading electricity between countries"],a:1,e:"Energy arbitrage means buying low and selling high, but with electricity. Run your miners when power is cheap (windy nights, near $0 per MWh) and shut down when it's expensive (hot afternoon peaks, $200+/MWh). You pocket the difference. MWh stands for megawatt-hour, the unit electricity is priced in on wholesale markets.",s:U.BS}
],
2:[
{q:"What are the four simultaneous revenue streams that GPS captures for data center operators?",o:["Solar, wind, hydro, nuclear energy sales","Energy arbitrage, ancillary services, demand response, and capacity payments","Hardware sales, software licensing, consulting fees, and maintenance contracts","Mining revenue, trading profits, lending income, and staking rewards"],a:1,e:"GPS captures revenue from four sources simultaneously using the same flexible load: (1) energy arbitrage (buy low, sell high), (2) ancillary services (grid stability backup), (3) demand response (paid to reduce usage), and (4) capacity payments (paid just for being available). Stacking all four is what makes GPS revenue so much higher than generic programs.",s:U.BR},
{q:"What is SPP (Southwest Power Pool), and how many US states does it cover?",o:["A solar panel provider covering 5 states","A regional power grid operator managing 14 central US states","A partnership of 8 southern states","A national power protocol covering all 50 states"],a:1,e:"SPP (Southwest Power Pool) is a regional grid operator managing electricity across 14 central US states and about 60,000 miles of high-voltage power lines. Think of it like the air traffic control for electricity in that region. GPS launched here first because SPP's market conditions are ideal for flexible load revenue.",s:U.BS},
{q:"Why does SPP's shrinking reserve margin (from 39% down to a projected 5%) benefit GPS customers?",o:["Shrinking reserves mean cheaper electricity for everyone","A tighter grid means higher payments for flexible load providers willing to reduce consumption during peaks","It doesn't affect GPS customers at all","Less reserve means less competition for GPS"],a:1,e:"Reserve margin is how much backup power the grid has beyond what it needs. SPP's dropped from 39% to a projected 5% by 2029. As that margin shrinks, the grid gets more desperate for flexible load providers willing to reduce consumption during peaks. More desperation = higher payments to GPS customers. Basic supply and demand.",s:U.BS},
{q:"How fast does GPS settle payments compared to traditional demand response providers?",o:["Same timeline for both","GPS: 30-45 days vs. traditional: 60-90 days","GPS pays weekly; traditional pays monthly","GPS pays instantly; traditional takes 30 days"],a:1,e:"GPS settles payments (sends the money) in 30-45 days, while traditional demand response programs take 60-90 days. For data center operators spending millions on electricity and equipment, getting paid a month sooner makes a real difference to their cash flow and ability to reinvest.",s:U.G},
{q:"What are 'ancillary services' in the context of power grid markets?",o:["Customer support and technical help desks","Grid stability services: operating reserves (standby backup) and frequency regulation (keeping the grid at 60 Hz)","Power line maintenance and repair crews","Billing and invoicing services for utilities"],a:1,e:"Ancillary services are the behind-the-scenes jobs that keep the power grid stable. Two main types: operating reserves (being on standby as backup power, like a hospital's on-call doctor) and frequency regulation (helping keep the grid at exactly 60 Hz, which is critical for everything to work). Both pay well because they're essential to grid reliability.",s:U.G},
{q:"How much additional annual revenue could GPS generate for a 50 MW data center facility?",o:["~$500K/year","~$1M/year","~$3.25 million/year","~$10M/year"],a:2,e:"The math: 50 MW times roughly $65,000 per MW per year equals about $3.25 million per year in additional revenue. That's money on top of whatever the data center is already earning from mining or AI computing. When you tell a prospect 'you're leaving $3 million a year on the table,' that gets their attention fast.",s:U.BR},
{q:"After SPP, which three power grid markets is GPS expanding into?",o:["Staying in SPP only for now","ERCOT (Texas), PJM (13 eastern states), and MISO (15 midwest states)","CAISO (California), NYISO (New York)","International markets in Europe and Asia"],a:1,e:"After SPP, GPS is expanding to three major grid markets: ERCOT (Texas, known for extreme price swings), PJM (the largest US grid covering 13 eastern states, home to the world's biggest data center corridor in Virginia), and MISO (Midcontinent, 15 midwest states). Each market represents a huge revenue opportunity.",s:U.GP},
{q:"Why does SPP's high wind energy generation specifically benefit GPS customers?",o:["Wind turbines are quieter for nearby data centers","Wind creates price volatility — near-zero prices on windy nights, $200+ spikes on calm hot days — which GPS exploits","Wind provides good landmarks for locating sites","Wind directly cools the data center equipment"],a:1,e:"SPP has massive wind farms. When the wind blows hard (especially at night), electricity prices drop near zero or even go negative. During calm, hot days, prices spike to $200+/MWh. GPS exploits these swings: run your operation when power is nearly free, shut down when it's expensive, and pocket the savings. More wind = more swings = more profit.",s:U.BS}
],
3:[
{q:"What are SPP's new Planning Reserve Margin requirements for summer and winter 2026?",o:["12% summer, 15% winter","16% summer, 36% winter","25% for both seasons","No change from previous years"],a:1,e:"SPP set new Planning Reserve Margins (the required backup capacity buffer) at 16% for summer 2026 and 36% for winter. Higher reserve margin requirements mean the grid needs more flexible load available, which means more payments flowing to GPS customers. Winter is higher because SPP has less predictable heating demand.",s:U.BS},
{q:"What makes ERCOT (the Texas power grid) unique among US grids, and why does that matter for GPS?",o:["ERCOT is the smallest US grid, covering only Houston","ERCOT is independent from the US grid and not regulated by FERC — creating extreme price volatility that GPS can exploit","ERCOT is a Texas-based transformer company","ERCOT is a type of transformer Giga manufactures"],a:1,e:"ERCOT (Electric Reliability Council of Texas) manages about 90% of Texas's electricity. It's uniquely independent from the US grid and not regulated by FERC (Federal Energy Regulatory Commission). This independence creates extreme price volatility, like the $9,000/MWh spikes during the 2021 winter storm. For GPS, volatility equals opportunity.",s:U.G},
{q:"What is PJM, and why is it a critical expansion market for GPS?",o:["A small regional grid in Pennsylvania","The largest US power grid: 13 states, 67 million customers, home to the world's biggest data center corridor","A payment network for energy transactions","A Giga competitor in the software space"],a:1,e:"PJM is the largest US power grid, spanning 13 states and serving 67 million customers. Northern Virginia, within PJM territory, is the world's largest data center corridor. That makes PJM expansion a massive market opportunity for GPS, because there are already huge concentrations of flexible-load data centers there.",s:U.G},
{q:"How does GPS factor in Bitcoin mining economics when deciding whether to curtail operations?",o:["It doesn't consider mining economics at all","It factors in hashprice, network difficulty, and breakeven thresholds — only curtailing when grid revenue exceeds mining revenue","It only tracks the current Bitcoin price","It mines Bitcoin directly on behalf of customers"],a:1,e:"GPS is smart about Bitcoin mining economics. It factors in hashprice (how much revenue each unit of mining power generates), network difficulty (how hard it is to mine), and breakeven cost. It only tells miners to shut down when the money from the grid exceeds what they'd earn mining. This ensures miners never leave money on the table either way.",s:U.G},
{q:"How does Giga's GPS hardware rebate model work as a sales tool?",o:["Free transformer with every GPS subscription","Multi-year GPS contracts unlock rebates on Giga hardware purchases — no competitor can match this bundle","A trade-in program for old equipment","Standard volume discounts unrelated to GPS"],a:1,e:"When customers sign multi-year GPS optimization contracts, they unlock rebates on Giga hardware purchases (transformers, switchboards, data centers). No competitor can offer this bundle because no one else makes both the hardware and the software platform. This is a powerful deal-closing tool in your sales kit.",s:U.G},
{q:"What is the single most effective GPS sales pitch, in one sentence?",o:["We offer the cheapest electricity rates in the country","You're leaving $40,000 to $60,000 per MW per year on the table compared to generic demand response","We have the newest software platform on the market","We're the biggest energy company in the US"],a:1,e:"The killer one-liner: 'You're leaving $40,000 to $60,000 per MW per year on the table.' That's the gap between what generic demand response programs pay (~$20K) and what GPS delivers ($60-80K). For a 50 MW operation, that gap is $2-3 million per year. Lead with this number in every GPS conversation.",s:U.BR}
]},
whale:[
{q:"A 50 MW Bitcoin miner in Oklahoma says: 'Our margins are getting crushed by electricity costs.' What's your best move?",o:["Recommend they upgrade to a bigger transformer","Introduce GPS: earn $50-80K/MW/year by monetizing their flexible load through SPP energy markets","Suggest they switch to solar power","Advise them to reduce their mining capacity"],a:1,e:"This customer's problem is electricity eating their margins. GPS directly solves that by generating ~$3.25M/year in energy market revenue for a 50 MW facility in SPP. Instead of just mining Bitcoin, they'd also be earning from the grid. Always lead with the dollar amount that matches the customer's problem.",s:U.G},
{q:"A developer says: 'I need to be online in 8 months. Everyone else says it's impossible.' How do you respond?",o:["That timeline isn't realistic for us either","Giga does it in 6-8 months — we manufacture everything in-house and manage the full buildout","We could probably do 3 months, no problem","You should lower your expectations to 18 months"],a:1,e:"Giga does 6-8 months because they make everything in-house (transformers, switchboards, data centers, site work). The industry standard is 24-36+ months because most companies have to coordinate between multiple vendors. 'Vertical integration' (owning the whole supply chain) is what makes the impossible timeline possible.",s:U.SD},
{q:"An engineer asks skeptically: 'Why should I trust a Bitcoin mining company to build my transformers?'",o:["Change the subject to pricing to avoid the question","1,000+ transformers built, 3.5+ GW delivered, 175 MW of our own sites running our equipment, full UL/IEEE/DOE compliance","Offer a steep discount to overcome their concerns","Mention the founders made Forbes 30 Under 30"],a:1,e:"When engineers question Giga's credibility, hit them with facts: 1,000+ transformers built, 3.5+ GW delivered, 175 MW of their own sites running on their own equipment, and full compliance with UL, IEEE, and DOE standards. The Bitcoin mining origin story is actually a strength because it shows they understand the customer's use case firsthand.",s:U.A},
{q:"A customer says: 'We can't wait 52 weeks for a transformer from our current vendor.' What's your solution?",o:["Tell them you might be able to do 40 weeks","In-stock units ship 1-2 business days from Long Beach. Custom builds take 12-14 weeks.","Suggest they check back next quarter","Explain that lead times are outside your control"],a:1,e:"When a customer says they can't wait, that's your opening. Giga has in-stock transformers shipping in 1-2 business days, and custom builds take 12-14 weeks. The industry average is 52-104+ weeks. Lead with speed, always. It's the single biggest reason customers choose Giga over established competitors.",s:U.S},
{q:"A utility company says: 'We need a 75 MVA substation for an industrial park. Can Giga handle that size?'",o:["Padmounts only go up to 10,000 kVA, so we can't help","Yes — Giga's HV substations handle up to 100 MVA at 69-138 kV, well within range","We'd need to outsource that to a partner","Giga only sells to data center customers"],a:1,e:"75 MVA (megavolt-amperes) is well within Giga's HV (high-voltage) substation range, which goes up to 100 MVA at 138 kV (kilovolts). Don't hesitate on utility-scale requests. Giga's product line handles projects from small residential all the way up to major infrastructure.",s:U.S},
{q:"A prospect says: 'Schneider gave us a lower quote on a switchboard.' How do you handle this?",o:["Match Schneider's price immediately","What's Schneider's lead time? 20-52 weeks vs. our 8-12. What does every month of delayed project revenue cost you?","Admit you can't compete with Schneider's pricing","Offer a 50% discount to win the deal"],a:1,e:"Never compete on unit price with Schneider. Instead, reframe: 'What does delayed revenue cost you?' If a customer's project earns $500K/month and Schneider takes 6 months longer, that's $3M in lost revenue. Giga's slightly higher unit price is nothing compared to months of delayed income. Always sell total cost of ownership, not sticker price.",s:U.S},
{q:"A GPU cloud provider asks: 'What makes Giga's HPC data center offering different from competitors?'",o:["Our containers are more visually attractive","Single vendor from transformer to data center to energy optimization. One throat to choke — one team, one call, no finger-pointing.","Our price per rack is the lowest in the market","Our containers are physically larger than anyone else's"],a:1,e:"The pitch for GPU cloud providers: 'One throat to choke.' Giga makes the transformer, switchboard, data center, handles site development, AND optimizes energy costs with GPS. No other company does all of it. That means one vendor to manage, one team to call when something needs fixing, and no finger-pointing between suppliers.",s:U.AI},
{q:"A Texas customer says: 'We're interested in GPS, but we're in ERCOT, not SPP.' What do you tell them?",o:["Sorry, GPS only works in SPP — can't help you yet","ERCOT expansion is planned, and Texas's extreme price volatility means even bigger GPS revenue potential. You'll want to be first in line.","ERCOT doesn't support demand response programs","Suggest they relocate their operations to Oklahoma"],a:1,e:"ERCOT (Texas grid) expansion is planned for GPS. Don't dismiss the customer. Texas's independent grid creates extreme price volatility (during the 2021 winter storm, prices hit $9,000/MWh). That volatility actually means even bigger GPS revenue potential than SPP. Frame it as: 'You're going to want to be first in line when we launch in ERCOT.'",s:U.GP},
{q:"A residential utility asks about distribution transformers for a new 400-home subdivision with underground power lines.",o:["Recommend a 3-phase padmount for the whole subdivision","Suggest a Giga Box Air data center","1-phase padmount transformers (up to 250 kVA, 35 kV) — Giga stocks them in Houston with 2-6 week availability","Recommend MV substations for each block"],a:2,e:"Residential subdivisions with underground power lines need 1-phase padmount transformers (up to 250 kVA, 35 kV). These are smaller, simpler units for homes rather than commercial buildings. Giga stocks them in Houston with 2-6 week availability. This is a different sale than data center equipment, but still volume business for Giga.",s:U.S},
{q:"A prospect says: 'We already have a demand response provider.' How do you make the case for switching to GPS?",o:["Say GPS has better branding and a nicer dashboard","Ask what they're earning per MW — generic programs get ~$20K, GPS gets $50-80K. That's $40-60K/MW left on the table every year.","Offer to match their current provider's price","Tell them demand response isn't worth the effort"],a:1,e:"When a prospect already has a demand response provider, don't trash the competitor. Ask: 'What are they earning you per MW?' Generic programs get around $20K. GPS gets $50-80K. That $40-60K gap per MW per year is the pitch. Add in faster settlements (30-45 days vs 60-90) and hardware rebates, and the switch becomes a no-brainer.",s:U.BR},
// New Whale scenarios
{q:"A mining operator says: 'We're running 5 sites across ERCOT and SPP but managing each one separately is a nightmare.' What do you offer?",o:["Suggest they consolidate to one site","GPS can manage all sites from one platform, optimizing each site for its local grid market simultaneously","Recommend they hire more site managers","That's not something Giga can help with"],a:1,e:"GPS isn't limited to one site. It can manage a portfolio of sites across multiple grid regions, optimizing each one for its local energy market conditions. For a multi-site operator, this means centralized management with localized optimization. The pitch: 'One platform, all your sites, maximum revenue from every grid you're in.'",s:U.G},
{q:"A prospect asks: 'We're building a new 20 MW site from scratch. What's the full Giga package look like?'",o:["We just sell individual products — you'd coordinate the project yourself","Full vertical integration: Giga handles site assessment, designs and manufactures transformers + switchboards, builds the data center, connects to grid, and optimizes revenue with GPS. One vendor, 6-8 months.","We'd need to bring in subcontractors for most of the work","Start with the transformer and figure out the rest later"],a:1,e:"This is where Giga's vertical integration pitch shines brightest. A greenfield 20 MW site is the dream deal: site development, transformers, switchboards, data centers, and GPS optimization, all from one company. The timeline (6-8 months vs. industry's 24-36+) and single point of accountability are the closers.",s:U.SD},
{q:"An AI startup CTO says: 'We need to scale from 5 MW to 40 MW of GPU compute, but we can't afford any downtime during the expansion.'",o:["Downtime during expansion is unavoidable — plan for it","Giga's modular approach means you add capacity in parallel — new pods come online without touching existing infrastructure","Suggest they wait until they need the full 40 MW before building anything","Recommend a competitor who specializes in expansions"],a:1,e:"Modular data centers solve the expansion-without-downtime problem. New Giga Box HPC pods are built, delivered, and connected alongside existing infrastructure. Nothing gets shut down. Each pod is independent. This modular add-on approach is a massive selling point for customers who can't afford to go offline.",s:U.AI},
{q:"A procurement manager says: 'Your switchboard is $90K but Eaton quoted us $75K.' How do you respond?",o:["Match the $75K price","Our switchboard arrives in 8-12 weeks; Eaton's takes 20-52+ weeks. If your project generates $200K/month in revenue, every month of delay costs more than the $15K difference.","Offer a 20% discount","Admit Eaton is the better value"],a:1,e:"Same principle as the Schneider objection: never compete on sticker price alone. The $15K savings on the switchboard is meaningless if the project is delayed 3-6 months waiting for Eaton to deliver. Frame it as total cost of ownership: equipment cost + delay cost + coordination risk. Giga wins that math every time.",s:U.S}
]};
